'use client';
import { ArrowRight, CircleAlert, CircleHelp, Copy, Download, ShieldCheck, X } from 'lucide-react';
import { useState } from 'react';
import type { Assessment } from '@/lib/scam-engine';

export function CheckResult({ result, onSOS, onClear }: { result: Assessment; onSOS: () => void; onClear: () => void }) {
  const [copied, setCopied] = useState(false);
  const [copyError, setCopyError] = useState(false);
  const Icon = result.verdict === 'likely-scam' || result.verdict === 'suspicious' ? CircleAlert : result.verdict === 'uncertain' ? CircleHelp : ShieldCheck;
  const report = ['SHOMAR Protect — Pattern check', result.title, result.summary, '', ...result.signals.map(s => `${s.title}: ${s.detail}`), '', 'NEXT STEPS', ...result.actions.map((a, i) => `${i + 1}. ${a}`), '', 'This is a limited pattern check, not live verification. No malware scan, reputation lookup, payment verification, or account access was performed.', `Checked: ${new Date(result.checkedAt).toLocaleString()}`].join('\n');
  async function copyReport(){try{await navigator.clipboard.writeText(report);setCopied(true);setCopyError(false);}catch{setCopyError(true);}}
  function downloadReport(){const url=URL.createObjectURL(new Blob([report],{type:'text/plain;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='shomar-check.txt';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <section className={`assessment ${result.verdict}`} aria-live="polite"><div className="result-heading"><span className="result-icon"><Icon size={26}/></span><div><span className="card-kicker">YOUR CHECK RESULT</span><h3>{result.title}</h3></div><button className="icon-button" aria-label="Close result" onClick={onClear}><X size={17}/></button></div><p className="result-summary">{result.summary}</p>{result.signals.length > 0 && <div className="result-evidence"><h4>What stood out</h4>{result.signals.map(signal => <div key={signal.id} className="signal"><span/><div><strong>{signal.title}</strong><p>{signal.detail}</p></div></div>)}</div>}{result.domains.length > 0 && <div className="domain-list"><span>Destination names found</span>{result.domains.map(domain => <code key={domain}>{domain}</code>)}<small>Shown as text so you don’t accidentally open them.</small></div>}<div className="result-next"><h4>What to do next</h4><ol>{result.actions.map(action => <li key={action}>{action}</li>)}</ol><button className="text-button" onClick={onSOS}>Get help with Cyber SOS<ArrowRight size={16}/></button></div><div className="result-tools"><button className="text-button" onClick={copyReport}><Copy size={14}/>{copied ? 'Copied' : 'Copy guidance'}</button><button className="text-button" onClick={downloadReport}><Download size={14}/>Save guidance</button></div>{copyError && <p role="status">Copying isn’t available here. Use Save guidance instead.</p>}<p className="result-limit">This check looks for a limited set of patterns. It does not visit the website, verify a sender or payment, scan malware, or check live threat databases.</p></section>;
}
