'use client';
import { Clock3, FileImage, Link2, MessageSquareText, ScanLine, ShoppingBag, Trash2 } from 'lucide-react';
import { Empty, EmptyHeader, EmptyMedia, EmptyTitle, EmptyDescription } from '@/components/ui/empty';
import type { HistoryItem } from '@/lib/local-state';
const labels = { 'likely-scam': 'Likely scam', suspicious: 'Needs a closer look', uncertain: 'Insufficient evidence', 'no-signals': 'No clear warning signs' };
const modes = { message: { icon: MessageSquareText, label: 'Message check' }, link: { icon: Link2, label: 'Link check' }, screenshot: { icon: FileImage, label: 'Screenshot text check' }, vendor: { icon: ShoppingBag, label: 'Vendor shield check' } };
export function HistoryView({ history, compact = false, onNew, onClear }: { history: HistoryItem[]; compact?: boolean; onNew: () => void; onClear: () => void }) {
  return <section className={compact ? 'recent-preview' : 'panel history-panel'}><div className="section-heading"><h2>Recent checks</h2>{history.length > 0 ? <button className="text-button muted-button" onClick={onClear}><Trash2 size={14}/>Clear history</button> : <span className="secondary-label">Only on this device</span>}</div>{history.length === 0 ? <Empty className={compact ? 'history-empty compact' : 'history-empty'}><EmptyHeader><EmptyMedia variant="icon"><Clock3/></EmptyMedia><EmptyTitle>A little reassurance starts here.</EmptyTitle><EmptyDescription>Your checks will appear here. The original messages, links, and images are never saved.</EmptyDescription></EmptyHeader>{!compact && <button className="primary-button" onClick={onNew}><ScanLine size={17}/>Make your first check</button>}</Empty> : <><ul className="history-list">{(compact ? history.slice(0, 3) : history).map(item => { const mode = modes[item.mode]; const Icon = mode.icon; return <li key={item.id}><span className="history-icon"><Icon size={18}/></span><div className="history-item-title"><strong>{mode.label}</strong><time dateTime={item.checkedAt}>{new Date(item.checkedAt).toLocaleString(undefined, { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })}</time></div><span className={`verdict-badge ${item.verdict}`}>{labels[item.verdict]}</span><span className="history-signal-count">{item.signals} {item.signals === 1 ? 'signal' : 'signals'}</span></li>; })}</ul>{!compact && <p className="history-note">The most recent 30 check summaries are stored in this browser. They do not sync to other devices.</p>}</>}</section>;
}
