'use client';
import { Check, Clock3, ExternalLink, ShieldCheck } from 'lucide-react';
import { Checkbox } from '@/components/ui/checkbox';
import { Progress } from '@/components/ui/progress';
import { protectionTasks } from '@/lib/safety-content';

export function ProtectionView({ done, onToggle }: { done: string[]; onToggle: (id: string, value: boolean) => void }) {
  const count = protectionTasks.filter(task => done.includes(task.id)).length;
  return <section className="protection-layout"><div className="panel checklist-panel"><div className="section-heading"><div><h2>Your everyday security checklist</h2><p className="section-description">Do the step in your own account, then tick it here.</p></div><span className="count-badge">{count} / {protectionTasks.length}</span></div><Progress value={count / protectionTasks.length * 100} aria-label={`${count} of ${protectionTasks.length} security steps complete`}/><div className="checklist">{protectionTasks.map(task => <div key={task.id} className={`checklist-row ${done.includes(task.id) ? 'is-done' : ''}`}><Checkbox id={`task-${task.id}`} checked={done.includes(task.id)} onCheckedChange={value => onToggle(task.id, value === true)} aria-label={`Mark ${task.title} as complete`}/><div><div className="task-meta"><span>{task.category}</span><span><Clock3 size={12}/>{task.minutes} min</span></div><label htmlFor={`task-${task.id}`} className="task-title">{task.title}</label><p>{task.description}</p>{'href' in task && <a className="text-button" href={task.href} target="_blank" rel="noopener noreferrer">{task.action}<ExternalLink size={13}/></a>}{'alternate' in task && <a className="text-button alternate-link" href={task.alternate.href} target="_blank" rel="noopener noreferrer">{task.alternate.label}<ExternalLink size={13}/></a>}</div></div>)}</div></div><aside><section className="readiness-card"><div className="card-kicker"><ShieldCheck size={17}/> STEP BY STEP</div><h2>{count === protectionTasks.length ? 'Good habits. A stronger start.' : 'Your digital life is worth a few minutes.'}</h2><p>{count === protectionTasks.length ? 'You’ve completed your checklist. Revisit it when you change accounts, devices, or recovery details.' : 'Start with your email. It’s often the key to recovering your other accounts.'}</p><div className="readiness-stat"><strong>{count}<span> / {protectionTasks.length}</span></strong><span>steps marked complete</span></div><Progress value={count / protectionTasks.length * 100} aria-label="Checklist progress"/><div className="self-reported"><Check size={12}/> Progress saved on this device</div></section><div className="tip-card protection-note"><h3>A checklist, updated by you.</h3><p>SHOMAR does not read your account settings or continuously monitor your accounts. These ticks reflect the steps you tell us you’ve taken.</p></div></aside></section>;
}
