'use client';
import { useState } from 'react';
import { ArrowLeft, ArrowRight, Check, ChevronRight, ExternalLink, LifeBuoy, Mail, MessageSquareText, Phone, ShieldCheck, Wallet } from 'lucide-react';
import { Progress } from '@/components/ui/progress';
import { Checkbox } from '@/components/ui/checkbox';
import { guides } from '@/lib/safety-content';

const icons = { message: MessageSquareText, mail: Mail, phone: Phone, wallet: Wallet, link: LifeBuoy };

export function RecoveryView({ guideId, onGuide, done, onToggle }: { guideId: string | null; onGuide: (id: string | null) => void; done: string[]; onToggle: (id: string, value: boolean) => void }) {
  const [step, setStep] = useState(0);
  const guide = guides.find(g => g.id === guideId);
  if (!guide) return <section className="sos-view"><div className="notice-banner"><LifeBuoy size={22}/><div><strong>You don’t have to figure it out all at once.</strong><p>Choose what happened. We’ll help you work through the next steps.</p></div></div><div className="guide-grid">{guides.map(g => { const Icon = icons[g.icon]; return <button className="guide-card panel" key={g.id} onClick={() => { setStep(0); onGuide(g.id); }}><span className="icon-tile coral"><Icon size={24}/></span><h2>{g.title}</h2><p>{g.description}</p><span className="guide-start">Start recovery guide <ArrowRight size={17}/></span></button>; })}</div><div className="sos-footnote"><ShieldCheck size={20}/><p>These are self-guided steps with official support links. SHOMAR cannot access your accounts, reverse payments, or guarantee recovery. No live agent is connected.</p></div></section>;
  const current = guide.steps[Math.min(step, guide.steps.length - 1)];
  const count = guide.steps.filter((_, i) => done.includes(`${guide.id}-${i}`)).length;
  return <section className="recovery-layout"><div><button className="text-button back-button" onClick={() => onGuide(null)}><ArrowLeft size={16}/>All recovery guides</button><div className="notice-banner urgent"><LifeBuoy size={22}/><p>{guide.urgent}</p></div><div className="panel step-panel"><div className="section-heading"><span className="eyebrow">STEP {step + 1} OF {guide.steps.length}</span><span className="secondary-label">{count} completed</span></div><Progress value={count / guide.steps.length * 100} aria-label={`${count} of ${guide.steps.length} steps marked complete`}/><h2>{current.title}</h2><p>{current.body}</p><div className="official-actions">{[current.action, current.secondary].filter(Boolean).map(a => a && <a key={a.href} className="outline-button" href={a.href} target="_blank" rel="noopener noreferrer">{a.label}<ExternalLink size={15}/></a>)}</div><label className="step-completion"><Checkbox checked={done.includes(`${guide.id}-${step}`)} onCheckedChange={checked => onToggle(`${guide.id}-${step}`, checked === true)}/><span>I’ve completed this step</span></label><div className="step-controls"><button className="outline-button" disabled={step === 0} onClick={() => setStep(n => Math.max(0, n - 1))}><ArrowLeft size={16}/>Back</button>{step < guide.steps.length - 1 ? <button className="primary-button" onClick={() => setStep(n => n + 1)}>Next step<ArrowRight size={16}/></button> : <button className="primary-button" onClick={() => onGuide(null)}>Back to guides<Check size={16}/></button>}</div>{count === guide.steps.length && <p className="completion-note"><Check size={16}/>You’ve marked every step complete. Continue following up with the relevant provider; this does not confirm the incident is resolved.</p>}</div><a className="source-link" href={guide.source.href} target="_blank" rel="noopener noreferrer">Based on {guide.source.label}<ExternalLink size={13}/></a></div><aside className="panel step-index"><span className="card-kicker">YOUR RECOVERY PLAN</span><h3>{guide.title}</h3><ol>{guide.steps.map((s, i) => <li key={s.title}><button className={step === i ? 'selected' : ''} aria-current={step === i ? 'step' : undefined} onClick={() => setStep(i)}><span className={done.includes(`${guide.id}-${i}`) ? 'done' : ''}>{done.includes(`${guide.id}-${i}`) ? <Check size={14}/> : i + 1}</span><span>{s.title}</span><ChevronRight size={15}/></button></li>)}</ol><p><LockNote/>Progress is saved on this device. You can return to any step.</p></aside></section>;
}
function LockNote(){return <ShieldCheck size={15}/>;}
