import { Pressable, StyleSheet, Text, View, type ViewStyle, type StyleProp } from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';
import type { ComponentProps, ReactNode } from 'react';

export const c = { navy: '#112541', blue: '#365FE9', ink: '#192C47', muted: '#5C6F87', line: '#DCE4EF', bg: '#F4F7FC', white: '#FFFFFF', good: '#177451', caution: '#805912', danger: '#AE3C3C', neutral: '#5C6F87' };
export type IconName = ComponentProps<typeof Ionicons>['name'];
export function Icon({ name, size = 22, color = c.ink }: { name: IconName; size?: number; color?: string }) { return <Ionicons name={name} size={size} color={color}/>; }
export function Copy({ children, muted = false }: { children: ReactNode; muted?: boolean }) { return <Text style={[s.body, muted && { color: c.muted }]}>{children}</Text>; }
export function Title({ children }: { children: ReactNode }) { return <Text accessibilityRole="header" style={s.title}>{children}</Text>; }
export function Card({ children, style }: { children: ReactNode; style?: StyleProp<ViewStyle> }) { return <View style={[s.card, style]}>{children}</View>; }
export function Button({ title, onPress, secondary = false, disabled = false, icon }: { title: string; onPress: () => void; secondary?: boolean; disabled?: boolean; icon?: IconName }) { return <Pressable accessibilityRole="button" accessibilityState={{ disabled }} disabled={disabled} onPress={onPress} style={({ pressed }) => [s.button, secondary && s.secondary, (pressed || disabled) && { opacity: .55 }]}>{icon && <Icon name={icon} color={secondary ? c.blue : c.white} size={20}/>}<Text style={[s.buttonText, secondary && { color: c.blue }]}>{title}</Text></Pressable>; }
export function Tick({ title, description, checked, onPress }: { title: string; description?: string; checked: boolean; onPress: () => void }) { return <Pressable onPress={onPress} accessibilityRole="checkbox" accessibilityState={{ checked }} style={({ pressed }) => [s.tick, pressed && { opacity: .65 }]}><Icon name={checked ? 'checkbox' : 'square-outline'} color={checked ? c.good : c.muted} size={25}/><View style={{ flex: 1, gap: 5 }}><Text style={s.label}>{title}</Text>{description && <Copy muted>{description}</Copy>}</View></Pressable>; }
export function Chips({ values, value, onChange }: { values: readonly string[]; value: string; onChange: (value: string) => void }) { return <View style={s.chips}>{values.map(x => <Pressable key={x} accessibilityRole="button" accessibilityState={{ selected: x === value }} onPress={() => onChange(x)} style={[s.chip, x === value && s.activeChip]}><Text style={[s.chipText, x === value && { color: c.blue }]}>{x}</Text></Pressable>)}</View>; }
export function Notice({ children }: { children: ReactNode }) { return <View style={s.notice}><Icon name="information-circle-outline" color={c.blue}/><Text style={[s.body, { flex: 1 }]}>{children}</Text></View>; }
export const s = StyleSheet.create({
  body: { fontSize: 16, lineHeight: 24, color: c.ink }, title: { fontSize: 26, lineHeight: 33, fontWeight: '700', color: c.ink, letterSpacing: -.5 }, h2: { fontSize: 19, lineHeight: 26, fontWeight: '700', color: c.ink }, label: { fontSize: 16, fontWeight: '600', lineHeight: 23, color: c.ink }, small: { fontSize: 13, lineHeight: 19, color: c.muted },
  card: { backgroundColor: c.white, borderWidth: 1, borderColor: c.line, borderRadius: 20, padding: 20, gap: 14 }, button: { minHeight: 50, backgroundColor: c.blue, borderRadius: 13, paddingHorizontal: 18, paddingVertical: 13, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9 }, secondary: { backgroundColor: '#EDF2FF', borderWidth: 1, borderColor: '#D6E0FF' }, buttonText: { color: c.white, fontSize: 16, lineHeight: 23, fontWeight: '600', flexShrink: 1, textAlign: 'center' },
  tick: { flexDirection: 'row', gap: 12, alignItems: 'flex-start', minHeight: 48, paddingVertical: 12 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, chip: { minHeight: 44, borderRadius: 12, borderWidth: 1, borderColor: c.line, backgroundColor: c.white, justifyContent: 'center', paddingHorizontal: 14, paddingVertical: 10 }, activeChip: { backgroundColor: '#EDF2FF', borderColor: '#AFC1FA' }, chipText: { fontSize: 14, lineHeight: 20, fontWeight: '600', color: c.muted },
  notice: { borderRadius: 14, backgroundColor: '#EAF1FC', borderWidth: 1, borderColor: '#D5E2F5', padding: 15, flexDirection: 'row', alignItems: 'flex-start', gap: 10 }, input: { fontSize: 16, lineHeight: 24, color: c.ink, padding: 14, borderWidth: 1, borderColor: c.line, backgroundColor: c.white, borderRadius: 13, minHeight: 50 }, row: { flexDirection: 'row', alignItems: 'center', gap: 12 }, stack: { gap: 18 }, hr: { height: 1, backgroundColor: c.line },
});
