export type BankPanicEntry = {
  id: string;
  name: string;
  shortName: string;
  ussdCode?: string;
  phoneHotline?: string;
  instructions: string;
  dialUri?: string;
  category: 'Commercial Bank' | 'Fintech / Neobank';
  country?: 'NG' | 'KE' | 'GH' | 'ZA' | 'Regional';
};

export const BANK_PANIC_DIRECTORY: BankPanicEntry[] = [
  {
    id: 'access',
    name: 'Access Bank',
    shortName: 'Access',
    ussdCode: '*901*911#',
    phoneHotline: '+23412712005',
    dialUri: 'tel:*901*911%23',
    category: 'Commercial Bank',
    instructions: 'Dial *901*911# from any phone. Enter the registered phone number linked to your account to freeze debit transactions immediately.',
  },
  {
    id: 'gtbank',
    name: 'Guaranty Trust Bank (GTBank)',
    shortName: 'GTBank',
    ussdCode: '*737*51*74#',
    phoneHotline: '+23414480000',
    dialUri: 'tel:*737*51*74%23',
    category: 'Commercial Bank',
    instructions: 'Dial *737*51*74# from any phone. Enter your phone number and 737 PIN to block all debit activities instantly.',
  },
  {
    id: 'zenith',
    name: 'Zenith Bank',
    shortName: 'Zenith',
    ussdCode: '*966*911#',
    phoneHotline: '+23412787000',
    dialUri: 'tel:*966*911%23',
    category: 'Commercial Bank',
    instructions: 'Dial *966*911# from any phone, enter your account number and registered phone number to restrict access.',
  },
  {
    id: 'firstbank',
    name: 'First Bank of Nigeria',
    shortName: 'First Bank',
    ussdCode: '*894*911#',
    phoneHotline: '+23419052326',
    dialUri: 'tel:*894*911%23',
    category: 'Commercial Bank',
    instructions: 'Dial *894*911# from any phone. Enter the phone number tied to your First Bank account to lock banking channels.',
  },
  {
    id: 'uba',
    name: 'United Bank for Africa (UBA)',
    shortName: 'UBA',
    ussdCode: '*919*911#',
    phoneHotline: '+23412808822',
    dialUri: 'tel:*919*911%23',
    category: 'Commercial Bank',
    instructions: 'Dial *919*911# from any mobile number to block debit card and mobile banking access instantly.',
  },
  {
    id: 'opay',
    name: 'OPay Digital Services',
    shortName: 'OPay',
    ussdCode: '*955*911#',
    phoneHotline: '+23418888329',
    dialUri: 'tel:*955*911%23',
    category: 'Fintech / Neobank',
    instructions: 'Dial *955*911# from any phone. Enter your OPay registered phone number to freeze your wallet immediately.',
  },
  {
    id: 'palmpay',
    name: 'PalmPay',
    shortName: 'PalmPay',
    ussdCode: '*861*911#',
    phoneHotline: '+23417005410',
    dialUri: 'tel:*861*911%23',
    category: 'Fintech / Neobank',
    instructions: 'Dial *861*911# from any mobile line. Follow the prompts with your PalmPay phone number to halt account operations.',
  },
  {
    id: 'moniepoint',
    name: 'Moniepoint Microfinance Bank',
    shortName: 'Moniepoint',
    ussdCode: '*5573*911#',
    phoneHotline: '+23418888450',
    dialUri: 'tel:*5573*911%23',
    category: 'Fintech / Neobank',
    instructions: 'Dial *5573*911# from any phone to immediately lock your POS, account, or card from unauthorized withdrawals.',
  },
  {
    id: 'kuda',
    name: 'Kuda Microfinance Bank',
    shortName: 'Kuda',
    phoneHotline: '+23416335832',
    dialUri: 'tel:+23416335832',
    category: 'Fintech / Neobank',
    instructions: 'Call Kuda fraud emergency line directly at 01 633 5832 or sign in on a trusted web browser to freeze your card in Security Settings.',
  },
  {
    id: 'fidelity',
    name: 'Fidelity Bank',
    shortName: 'Fidelity',
    ussdCode: '*770*911#',
    phoneHotline: '+23414485252',
    dialUri: 'tel:*770*911%23',
    category: 'Commercial Bank',
    instructions: 'Dial *770*911# from any phone. Provide your account number to freeze electronic debits immediately.',
  },
  {
    id: 'stanbic',
    name: 'Stanbic IBTC Bank',
    shortName: 'Stanbic',
    ussdCode: '*909*911#',
    phoneHotline: '+23414222222',
    dialUri: 'tel:*909*911%23',
    category: 'Commercial Bank',
    instructions: 'Dial *909*911# from any mobile device to block transactions across your accounts.',
  },
  {
    id: 'wema',
    name: 'Wema Bank / ALAT',
    shortName: 'Wema / ALAT',
    ussdCode: '*945*911#',
    phoneHotline: '+234180022552528',
    dialUri: 'tel:*945*911%23',
    category: 'Commercial Bank',
    instructions: 'Dial *945*911# from any phone. Enter the phone number tied to your Wema or ALAT account to freeze debits.',
  },
  {
    id: 'sterling',
    name: 'Sterling Bank',
    shortName: 'Sterling',
    ussdCode: '*822*911#',
    phoneHotline: '+23417003270',
    dialUri: 'tel:*822*911%23',
    category: 'Commercial Bank',
    instructions: 'Dial *822*911# and enter the phone number registered on the account to lock your profile.',
  },
  {
    id: 'union',
    name: 'Union Bank',
    shortName: 'Union',
    ussdCode: '*826*911#',
    phoneHotline: '+23412716816',
    dialUri: 'tel:*826*911%23',
    category: 'Commercial Bank',
    instructions: 'Dial *826*911# from any mobile line and follow the prompt to place a debit restriction on the account.',
  },
  {
    id: 'fcmb',
    name: 'FCMB',
    shortName: 'FCMB',
    ussdCode: '*329*911#',
    phoneHotline: '+23412798800',
    dialUri: 'tel:*329*911%23',
    category: 'Commercial Bank',
    instructions: 'Dial *329*911# to block card and mobile banking on your FCMB account.',
  },
  {
    id: 'ecobank',
    name: 'Ecobank Nigeria',
    shortName: 'Ecobank',
    ussdCode: '*326*911#',
    phoneHotline: '+23412701350',
    dialUri: 'tel:*326*911%23',
    category: 'Commercial Bank',
    instructions: 'Dial *326*911# from any phone to freeze online banking and card transactions.',
    country: 'NG',
  },
  // Kenya
  {
    id: 'safaricom-mpesa',
    name: 'Safaricom M-Pesa (Kenya)',
    shortName: 'M-Pesa (KE)',
    ussdCode: '*100*100#',
    phoneHotline: '+254722000000',
    dialUri: 'tel:*100*100%23',
    category: 'Fintech / Neobank',
    country: 'KE',
    instructions: 'Dial *100*100# from any Safaricom line to activate emergency SIM swap protection, or call 234/100 to report fraudulent transactions.',
  },
  {
    id: 'equity-ke',
    name: 'Equity Bank Kenya',
    shortName: 'Equity (KE)',
    ussdCode: '*247#',
    phoneHotline: '+254763000000',
    dialUri: 'tel:*247%23',
    category: 'Commercial Bank',
    country: 'KE',
    instructions: 'Dial *247# to manage account security or call 0763 000 000 immediately to place a debit freeze.',
  },
  {
    id: 'kcb-ke',
    name: 'KCB Bank Kenya',
    shortName: 'KCB (KE)',
    ussdCode: '*522#',
    phoneHotline: '+254711087000',
    dialUri: 'tel:*522%23',
    category: 'Commercial Bank',
    country: 'KE',
    instructions: 'Dial *522# or contact the 24/7 contact center on +254 711 087000 to halt suspicious debit activity.',
  },
  {
    id: 'coop-ke',
    name: 'Co-operative Bank of Kenya',
    shortName: 'Co-op (KE)',
    ussdCode: '*667#',
    phoneHotline: '+254703027000',
    dialUri: 'tel:*667%23',
    category: 'Commercial Bank',
    country: 'KE',
    instructions: 'Dial *667# or call +254 703 027000 to lock MCo-op cash and card operations.',
  },
  // Ghana
  {
    id: 'mtn-momo-gh',
    name: 'MTN Mobile Money (Ghana)',
    shortName: 'MTN MoMo (GH)',
    ussdCode: '*170#',
    phoneHotline: '+233244300000',
    dialUri: 'tel:*170%23',
    category: 'Fintech / Neobank',
    country: 'GH',
    instructions: 'Dial *170# to manage wallet PIN, or call toll-free 100 to freeze your MoMo account immediately if under attack.',
  },
  {
    id: 'telecel-cash-gh',
    name: 'Telecel Cash / Vodafone Ghana',
    shortName: 'Telecel (GH)',
    ussdCode: '*110#',
    phoneHotline: '+233505555111',
    dialUri: 'tel:*110%23',
    category: 'Fintech / Neobank',
    country: 'GH',
    instructions: 'Dial *110# or call 100 from your Telecel SIM to restrict wallet cash-out and withdrawals.',
  },
  {
    id: 'gcb-gh',
    name: 'GCB Bank Ghana',
    shortName: 'GCB (GH)',
    ussdCode: '*422#',
    phoneHotline: '+233302681531',
    dialUri: 'tel:*422%23',
    category: 'Commercial Bank',
    country: 'GH',
    instructions: 'Dial *422# to lock mobile banking or reach customer contact center to stop debit cards.',
  },
  // South Africa
  {
    id: 'capitec-za',
    name: 'Capitec Bank (South Africa)',
    shortName: 'Capitec (ZA)',
    ussdCode: '*120*3279#',
    phoneHotline: '+27860102043',
    dialUri: 'tel:*120*3279%23',
    category: 'Commercial Bank',
    country: 'ZA',
    instructions: 'Dial *120*3279# or call 0860 10 20 43 immediately to stop all lost cards and freeze mobile app access.',
  },
  {
    id: 'fnb-za',
    name: 'First National Bank (South Africa)',
    shortName: 'FNB (ZA)',
    ussdCode: '*120*321#',
    phoneHotline: '+27875759404',
    dialUri: 'tel:*120*321%23',
    category: 'Commercial Bank',
    country: 'ZA',
    instructions: 'Dial *120*321# or call the FNB Fraud Line at 087 575 9404 to stop unauthorized EFT or card drains.',
  },
  {
    id: 'standardbank-za',
    name: 'Standard Bank (South Africa)',
    shortName: 'Standard (ZA)',
    ussdCode: '*120*2345#',
    phoneHotline: '+27800020600',
    dialUri: 'tel:*120*2345%23',
    category: 'Commercial Bank',
    country: 'ZA',
    instructions: 'Dial *120*2345# or call the toll-free fraud helpline at 0800 020 600 to place a stop on your account.',
  },
  {
    id: 'nedbank-za',
    name: 'Nedbank (South Africa)',
    shortName: 'Nedbank (ZA)',
    ussdCode: '*120*001#',
    phoneHotline: '+27800110929',
    dialUri: 'tel:*120*001%23',
    category: 'Commercial Bank',
    country: 'ZA',
    instructions: 'Dial *120*001# or phone the Nedbank Fraud Desk on 0800 110 929 to suspend banking channels.',
  },
];

export const SUPPORTED_COUNTRIES = [
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪' },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭' },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦' },
] as const;

export function getBanksByCountry(countryCode: string): BankPanicEntry[] {
  const norm = countryCode.toUpperCase();
  return BANK_PANIC_DIRECTORY.filter(b => (b.country || 'NG') === norm);
}
